PLATFORM = 'xb'
FUTHEAD_URL = f'https://www.futhead.com/21/players/?bin_platform={PLATFORM}'
FUTHEAD_NO_PLATFORM_URL = 'https://www.futhead.com/21/players/?group=all'
FUTHEAD_BASE_URL = 'https://futhead.com'
GK_URL = 'https://www.futhead.com/21/players/?group=gk'
